
-- +migrate Up
ALTER TABLE users ADD COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN `deleted_at` TIMESTAMP NULL DEFAULT NULL;
-- +migrate Down
ALTER TABLE users DROP COLUMN `created_at`;
ALTER TABLE users DROP COLUMN `updated_at`;
ALTER TABLE users DROP COLUMN `deleted_at`;
