
-- +migrate Up
CREATE TABLE IF NOT EXISTS `users` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL
);

-- +migrate Down
DROP TABLE IF EXISTS `users`;

